version: "3.1"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3080:3080
    container_name: imuber-backend
    networks:
      - mern-stack-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - mern-stack-net
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - mern-stack-net
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
